### ISSUE TITLE
Infusion Crystal Dupe?

### ISSUE THREAD

**Issue by littlebear22** [Electrolyte220/MysticalAgricultureTieredCrystals#3]
**What is the bug?**
Unsure if this is actually intended, if so apologies and please disregard this report.  When you craft the successive tiers of Infusion Crystals, the previous tier's crystal is not used up.  Only a single charge is used.   I expected the Inferium Infusion Crystal, for example, to be used up when crafting the Prudentium Infusion Crystal, and it was not.  So I ended up with twice as many crystals as expected.

**Steps to reproduce**
Using a crafting grid (AE2 or Regular, I tested both) place all elements to craft a Prudentium Infusion Crystal, including a fully repaired Inferium Crystal.  Craft, and the Inferium Crystal remains in the crafting grid minus one charge.

**Version**
Forge Ver:14.23.5.2811
Mystical Agriculture Ver:1.7.1
Mystical Aggridditions Ver:1.3.0

**Misc. Information**
Modpack is All The Mods 3: Remix

**Comment by Electrolyte220** [comment]
This behavior is intended.
