### ISSUE TITLE
The infusion crystals do not work for lower tier infusions, nor are they rechargeable. This means a lot of diamonds get wasted on creating the base tier which never get upgraded.

### ISSUE THREAD

**Issue by nickh4** [Electrolyte220/MysticalAgricultureTieredCrystals#6]

**Comment by Electrolyte220** [comment]
Hi, 
As for the repairing part: I'm not sure what you mean by this, as their are 2 ways to repair the infusion crystal from MA: 
1. Use a mending book.
2. Use an anvil to combine broken infusion crystals.
The tiered crystals can be repaired using either of the above methods.

As for the lower tier infusion part, the infusion crystals not working on lower tiers is a design choice.
