### ISSUE TITLE
1.20.1 Updates to AG

### ISSUE THREAD

**Issue by MokahTGS** [Electrolyte220/MysticalAgricultureTieredCrystals#7]
Has this been confirmed to work with the newest updates to Mystical Agriculture?  Other add-on are crashing with the new updates.

**Comment by Electrolyte220** [comment]
Hi,
I just tested with the latest versions of MA without any crashes:
Forge: 47.2.0
Cucumber: 7.0.6
Mystical Agriculture: 7.0.7
Mystical Agradditions: 7.0.2
